In [ ]:
import pandas as pd
from pathlib import Path

In [ ]:
from google.colab import files

uploaded = files.upload()

Saving olist_customers_dataset.csv to olist_customers_dataset.csv
Saving olist_geolocation_dataset.csv to olist_geolocation_dataset.csv
Saving olist_order_items_dataset.csv to olist_order_items_dataset.csv
Saving olist_order_payments_dataset.csv to olist_order_payments_dataset.csv
Saving olist_order_reviews_dataset.csv to olist_order_reviews_dataset.csv
Saving olist_orders_dataset.csv to olist_orders_dataset.csv
Saving olist_products_dataset.csv to olist_products_dataset.csv
Saving olist_sellers_dataset.csv to olist_sellers_dataset.csv
Saving product_category_name_translation.csv to product_category_name_translation.csv

In [ ]:
print(uploaded.keys())

dict_keys(['olist_customers_dataset.csv', 'olist_geolocation_dataset.csv', 'olist_order_items_dataset.csv', 'olist_order_payments_dataset.csv', 'olist_order_reviews_dataset.csv', 'olist_orders_dataset.csv', 'olist_products_dataset.csv', 'olist_sellers_dataset.csv', 'product_category_name_translation.csv'])

In [ ]:
for name, df in datasets.items():
    print("=" * 80)
    print(f"Dataset: {name}")
    print("=" * 80)

    print(f"Rows    : {df.shape[0]:,}")
    print(f"Columns : {df.shape[1]}")

    print("\nData Types:")
    print(df.dtypes)

    print("\nMissing Values:")
    print(df.isnull().sum())

    print("\nDuplicate Rows:")
    print(df.duplicated().sum())

    print("\n" + "-" * 80 + "\n")

NameError: name 'datasets' is not defined

In [ ]:
datasets = {}

for file_name in uploaded.keys():
    datasets[file_name.replace(".csv", "")] = pd.read_csv(file_name)

In [ ]:
datasets.keys()

dict_keys(['olist_customers_dataset', 'olist_geolocation_dataset', 'olist_order_items_dataset', 'olist_order_payments_dataset', 'olist_order_reviews_dataset', 'olist_orders_dataset', 'olist_products_dataset', 'olist_sellers_dataset', 'product_category_name_translation'])

In [ ]:
for name, df in datasets.items():
    print("=" * 100)
    print(f"Dataset: {name}")
    print("=" * 100)

    print(f"Shape: {df.shape}")

    print("\nData Types:")
    print(df.dtypes)

    print("\nMissing Values:")
    print(df.isnull().sum())

    print("\nDuplicate Rows:")
    print(df.duplicated().sum())

    print("\nFirst 5 Rows:")
    display(df.head())

    print("\n")

====================================================================================================
Dataset: olist_customers_dataset
====================================================================================================
Shape: (99441, 5)

Data Types:
customer_id                 object
customer_unique_id          object
customer_zip_code_prefix     int64
customer_city               object
customer_state              object
dtype: object

Missing Values:
customer_id                 0
customer_unique_id          0
customer_zip_code_prefix    0
customer_city               0
customer_state              0
dtype: int64

Duplicate Rows:
0

First 5 Rows:

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
0,06b8999e2fba1a1fbc88172c00ba8bc7,861eff4711a542e4b93843c6dd7febb0,14409,franca,SP
1,18955e83d337fd6b2def6b18a428ac77,290c77bc529b7ac935b93aa66c333dc3,9790,sao bernardo do campo,SP
2,4e7b3e00288586ebd08712fdd0374a03,060e732b5b29e8181a18229c7b0b2b5e,1151,sao paulo,SP
3,b2b6027bc5c5109e529d4dc6358b12c3,259dac757896d24d7702b9acbbff3f3c,8775,mogi das cruzes,SP
4,4f2d8ab171c80ec8364f7c12e35b23ad,345ecd01c38d18a9036ed96c73b8d066,13056,campinas,SP

====================================================================================================
Dataset: olist_geolocation_dataset
====================================================================================================
Shape: (1000163, 5)

Data Types:
geolocation_zip_code_prefix      int64
geolocation_lat                float64
geolocation_lng                float64
geolocation_city                object
geolocation_state               object
dtype: object

Missing Values:
geolocation_zip_code_prefix    0
geolocation_lat                0
geolocation_lng                0
geolocation_city               0
geolocation_state              0
dtype: int64

Duplicate Rows:
261831

First 5 Rows:

,geolocation_zip_code_prefix,geolocation_lat,geolocation_lng,geolocation_city,geolocation_state
0,1037,-23.545621,-46.639292,sao paulo,SP
1,1046,-23.546081,-46.644820,sao paulo,SP
2,1046,-23.546129,-46.642951,sao paulo,SP
3,1041,-23.544392,-46.639499,sao paulo,SP
4,1035,-23.541578,-46.641607,sao paulo,SP

====================================================================================================
Dataset: olist_order_items_dataset
====================================================================================================
Shape: (112650, 7)

Data Types:
order_id                object
order_item_id            int64
product_id              object
seller_id               object
shipping_limit_date     object
price                  float64
freight_value          float64
dtype: object

Missing Values:
order_id               0
order_item_id          0
product_id             0
seller_id              0
shipping_limit_date    0
price                  0
freight_value          0
dtype: int64

Duplicate Rows:
0

First 5 Rows:

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-09-19 09:45:35,58.90,13.29
1,00018f77f2f0320c557190d7a144bdd3,1,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,2017-05-03 11:05:13,239.90,19.93
2,000229ec398224ef6ca0657da4fc703e,1,c777355d18b72b67abbeef9df44fd0fd,5b51032eddd242adc84c38acab88f23d,2018-01-18 14:48:30,199.00,17.87
3,00024acbcdf0a6daa1e931b038114c75,1,7634da152a4610f1595efa32f14722fc,9d7a1d34a5052409006425275ba1c2b4,2018-08-15 10:10:18,12.99,12.79
4,00042b26cf59d7ce69dfabb4e55b4fd9,1,ac6c3623068f30de03045865e4e10089,df560393f3a51e74553ab94004ba5c87,2017-02-13 13:57:51,199.90,18.14

====================================================================================================
Dataset: olist_order_payments_dataset
====================================================================================================
Shape: (103886, 5)

Data Types:
order_id                 object
payment_sequential        int64
payment_type             object
payment_installments      int64
payment_value           float64
dtype: object

Missing Values:
order_id                0
payment_sequential      0
payment_type            0
payment_installments    0
payment_value           0
dtype: int64

Duplicate Rows:
0

First 5 Rows:

,order_id,payment_sequential,payment_type,payment_installments,payment_value
0,b81ef226f3fe1789b1e8b2acac839d17,1,credit_card,8,99.33
1,a9810da82917af2d9aefd1278f1dcfa0,1,credit_card,1,24.39
2,25e8ea4e93396b6fa0d3dd708e76c1bd,1,credit_card,1,65.71
3,ba78997921bbcdc1373bb41e913ab953,1,credit_card,8,107.78
4,42fdf880ba16b47b59251dd489d4441a,1,credit_card,2,128.45

====================================================================================================
Dataset: olist_order_reviews_dataset
====================================================================================================
Shape: (99224, 7)

Data Types:
review_id                  object
order_id                   object
review_score                int64
review_comment_title       object
review_comment_message     object
review_creation_date       object
review_answer_timestamp    object
dtype: object

Missing Values:
review_id                      0
order_id                       0
review_score                   0
review_comment_title       87656
review_comment_message     58247
review_creation_date           0
review_answer_timestamp        0
dtype: int64

Duplicate Rows:
0

First 5 Rows:

,review_id,order_id,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp
0,7bc2406110b926393aa56f80a40eba40,73fc7af87114b39712e6da79b0a377eb,4,NaN,NaN,2018-01-18 00:00:00,2018-01-18 21:46:59
1,80e641a11e56f04c1ad469d5645fdfde,a548910a1c6147796b98fdf73dbeba33,5,NaN,NaN,2018-03-10 00:00:00,2018-03-11 03:05:13
2,228ce5500dc1d8e020d8d1322874b6f0,f9e4b658b201a9f2ecdecbb34bed034b,5,NaN,NaN,2018-02-17 00:00:00,2018-02-18 14:36:24
3,e64fb393e7b32834bb789ff8bb30750e,658677c97b385a9be170737859d3511b,5,NaN,Recebi bem antes do prazo estipulado.,2017-04-21 00:00:00,2017-04-21 22:02:06
4,f7c4243c7fe1938f181bec41a392bdeb,8e6bfb81e283fa7e4f11123a3fb894f1,5,NaN,Parabéns lojas lannister adorei comprar pela I...,2018-03-01 00:00:00,2018-03-02 10:26:53

====================================================================================================
Dataset: olist_orders_dataset
====================================================================================================
Shape: (99441, 8)

Data Types:
order_id                         object
customer_id                      object
order_status                     object
order_purchase_timestamp         object
order_approved_at                object
order_delivered_carrier_date     object
order_delivered_customer_date    object
order_estimated_delivery_date    object
dtype: object

Missing Values:
order_id                            0
customer_id                         0
order_status                        0
order_purchase_timestamp            0
order_approved_at                 160
order_delivered_carrier_date     1783
order_delivered_customer_date    2965
order_estimated_delivery_date       0
dtype: int64

Duplicate Rows:
0

First 5 Rows:

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04 00:00:00
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15 00:00:00
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26 00:00:00

====================================================================================================
Dataset: olist_products_dataset
====================================================================================================
Shape: (32951, 9)

Data Types:
product_id                     object
product_category_name          object
product_name_lenght           float64
product_description_lenght    float64
product_photos_qty            float64
product_weight_g              float64
product_length_cm             float64
product_height_cm             float64
product_width_cm              float64
dtype: object

Missing Values:
product_id                      0
product_category_name         610
product_name_lenght           610
product_description_lenght    610
product_photos_qty            610
product_weight_g                2
product_length_cm               2
product_height_cm               2
product_width_cm                2
dtype: int64

Duplicate Rows:
0

First 5 Rows:

,product_id,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
0,1e9e8ef04dbcff4541ed26657ea517e5,perfumaria,40.0,287.0,1.0,225.0,16.0,10.0,14.0
1,3aa071139cb16b67ca9e5dea641aaa2f,artes,44.0,276.0,1.0,1000.0,30.0,18.0,20.0
2,96bd76ec8810374ed1b65e291975717f,esporte_lazer,46.0,250.0,1.0,154.0,18.0,9.0,15.0
3,cef67bcfe19066a932b7673e239eb23d,bebes,27.0,261.0,1.0,371.0,26.0,4.0,26.0
4,9dc1a7de274444849c219cff195d0b71,utilidades_domesticas,37.0,402.0,4.0,625.0,20.0,17.0,13.0

====================================================================================================
Dataset: olist_sellers_dataset
====================================================================================================
Shape: (3095, 4)

Data Types:
seller_id                 object
seller_zip_code_prefix     int64
seller_city               object
seller_state              object
dtype: object

Missing Values:
seller_id                 0
seller_zip_code_prefix    0
seller_city               0
seller_state              0
dtype: int64

Duplicate Rows:
0

First 5 Rows:

,seller_id,seller_zip_code_prefix,seller_city,seller_state
0,3442f8959a84dea7ee197c632cb2df15,13023,campinas,SP
1,d1b65fc7debc3361ea86b5f14c68d2e2,13844,mogi guacu,SP
2,ce3ad9de960102d0677a81f5d0bb7b2d,20031,rio de janeiro,RJ
3,c0f3eea2e14555b6faeea3dd58c1b1c3,4195,sao paulo,SP
4,51a04a8a6bdcb23deccc82b0b80742cf,12914,braganca paulista,SP

====================================================================================================
Dataset: product_category_name_translation
====================================================================================================
Shape: (71, 2)

Data Types:
product_category_name            object
product_category_name_english    object
dtype: object

Missing Values:
product_category_name            0
product_category_name_english    0
dtype: int64

Duplicate Rows:
0

First 5 Rows:

    product_category_name product_category_name_english
0            beleza_saude                 health_beauty
1  informatica_acessorios         computers_accessories
2              automotivo                          auto
3         cama_mesa_banho                bed_bath_table
4        moveis_decoracao               furniture_decor

In [ ]:
audit = []

for name, df in datasets.items():
    audit.append({
        "Dataset": name,
        "Rows": df.shape[0],
        "Columns": df.shape[1],
        "Missing Values": df.isnull().sum().sum(),
        "Duplicate Rows": df.duplicated().sum()
    })

audit_df = pd.DataFrame(audit)
audit_df

,Dataset,Rows,Columns,Missing Values,Duplicate Rows
0,olist_customers_dataset,99441,5,0,0
1,olist_geolocation_dataset,1000163,5,0,261831
2,olist_order_items_dataset,112650,7,0,0
3,olist_order_payments_dataset,103886,5,0,0
4,olist_order_reviews_dataset,99224,7,145903,0
5,olist_orders_dataset,99441,8,4908,0
6,olist_products_dataset,32951,9,2448,0
7,olist_sellers_dataset,3095,4,0,0
8,product_category_name_translation,71,2,0,0

In [ ]:
for name, df in datasets.items():
    missing = df.isnull().sum()

    if missing.sum() > 0:
        print(f"\n{name}")
        print(missing[missing > 0])

olist_order_reviews_dataset
review_comment_title      87656
review_comment_message    58247
dtype: int64

olist_orders_dataset
order_approved_at                 160
order_delivered_carrier_date     1783
order_delivered_customer_date    2965
dtype: int64

olist_products_dataset
product_category_name         610
product_name_lenght           610
product_description_lenght    610
product_photos_qty            610
product_weight_g                2
product_length_cm               2
product_height_cm               2
product_width_cm                2
dtype: int64

In [ ]:
orders = datasets["olist_orders_dataset"]

date_columns = [
    "order_purchase_timestamp",
    "order_approved_at",
    "order_delivered_carrier_date",
    "order_delivered_customer_date",
    "order_estimated_delivery_date"
]

for col in date_columns:
    orders[col] = pd.to_datetime(orders[col])

datasets["olist_orders_dataset"] = orders

In [ ]:
orders[date_columns].dtypes

order_purchase_timestamp         datetime64[ns]
order_approved_at                datetime64[ns]
order_delivered_carrier_date     datetime64[ns]
order_delivered_customer_date    datetime64[ns]
order_estimated_delivery_date    datetime64[ns]
dtype: object

In [ ]:
orders = datasets["olist_orders_dataset"].copy()

orders["order_year"] = orders["order_purchase_timestamp"].dt.year
orders["order_quarter"] = orders["order_purchase_timestamp"].dt.quarter
orders["order_month"] = orders["order_purchase_timestamp"].dt.month
orders["order_month_name"] = orders["order_purchase_timestamp"].dt.month_name()
orders["order_day"] = orders["order_purchase_timestamp"].dt.day
orders["order_day_name"] = orders["order_purchase_timestamp"].dt.day_name()
orders["order_week"] = orders["order_purchase_timestamp"].dt.isocalendar().week.astype("int")
orders["order_weekday"] = orders["order_purchase_timestamp"].dt.weekday

datasets["olist_orders_dataset"] = orders

In [ ]:
orders.head()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,order_year,order_quarter,order_month,order_month_name,order_day,order_day_name,order_week,order_weekday
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18,2017,4,10,October,2,Monday,40,0
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13,2018,3,7,July,24,Tuesday,30,1
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04,2018,3,8,August,8,Wednesday,32,2
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15,2017,4,11,November,18,Saturday,46,5
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26,2018,1,2,February,13,Tuesday,7,1

In [ ]:
orders = datasets["olist_orders_dataset"].copy()

orders["delivery_days"] = (
    orders["order_delivered_customer_date"] -
    orders["order_purchase_timestamp"]
).dt.days

datasets["olist_orders_dataset"] = orders

In [ ]:
orders[[
    "order_purchase_timestamp",
    "order_delivered_customer_date",
    "delivery_days"
]].head(10)

  order_purchase_timestamp order_delivered_customer_date  delivery_days
0      2017-10-02 10:56:33           2017-10-10 21:25:13            8.0
1      2018-07-24 20:41:37           2018-08-07 15:27:45           13.0
2      2018-08-08 08:38:49           2018-08-17 18:06:29            9.0
3      2017-11-18 19:28:06           2017-12-02 00:28:42           13.0
4      2018-02-13 21:18:39           2018-02-16 18:17:02            2.0
5      2017-07-09 21:57:05           2017-07-26 10:57:55           16.0
6      2017-04-11 12:22:08                           NaT            NaN
7      2017-05-16 13:10:30           2017-05-26 12:55:51            9.0
8      2017-01-23 18:29:09           2017-02-02 14:08:10            9.0
9      2017-07-29 11:55:02           2017-08-16 17:14:30           18.0

In [ ]:
orders["delay_days"] = (
    orders["order_delivered_customer_date"] -
    orders["order_estimated_delivery_date"]
).dt.days

In [ ]:
orders["delivery_status"] = orders["delay_days"].apply(
    lambda x: "Early" if x < 0
    else "On Time" if x == 0
    else "Late"
)

In [ ]:
order_items = datasets["olist_order_items_dataset"].copy()
orders = datasets["olist_orders_dataset"].copy()

fact_sales = order_items.merge(
    orders,
    on="order_id",
    how="left"
)

fact_sales.head()

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value,customer_id,order_status,order_purchase_timestamp,...,order_quarter,order_month,order_month_name,order_day,order_day_name,order_week,order_weekday,delivery_days,delay_days,delivery_status
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-09-19 09:45:35,58.90,13.29,3ce436f183e68e07877b285a838db11a,delivered,2017-09-13 08:59:02,...,3,9,September,13,Wednesday,37,2,7.0,-9.0,Early
1,00018f77f2f0320c557190d7a144bdd3,1,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,2017-05-03 11:05:13,239.90,19.93,f6dd3ec061db4e3987629fe6b26e5cce,delivered,2017-04-26 10:53:06,...,2,4,April,26,Wednesday,17,2,16.0,-3.0,Early
2,000229ec398224ef6ca0657da4fc703e,1,c777355d18b72b67abbeef9df44fd0fd,5b51032eddd242adc84c38acab88f23d,2018-01-18 14:48:30,199.00,17.87,6489ae5e4333f3693df5ad4372dab6d3,delivered,2018-01-14 14:33:31,...,1,1,January,14,Sunday,2,6,7.0,-14.0,Early
3,00024acbcdf0a6daa1e931b038114c75,1,7634da152a4610f1595efa32f14722fc,9d7a1d34a5052409006425275ba1c2b4,2018-08-15 10:10:18,12.99,12.79,d4eb9395c8c0431ee92fce09860c5a06,delivered,2018-08-08 10:00:35,...,3,8,August,8,Wednesday,32,2,6.0,-6.0,Early
4,00042b26cf59d7ce69dfabb4e55b4fd9,1,ac6c3623068f30de03045865e4e10089,df560393f3a51e74553ab94004ba5c87,2017-02-13 13:57:51,199.90,18.14,58dbd0b2d70206bf40e62cd34e84d795,delivered,2017-02-04 13:57:51,...,1,2,February,4,Saturday,5,5,25.0,-16.0,Early

In [ ]:
print(fact_sales.shape)

(112650, 25)

In [ ]:
print("Order Items Shape:", order_items.shape)
print("Fact Sales Shape :", fact_sales.shape)

Order Items Shape: (112650, 7)
Fact Sales Shape : (112650, 25)

In [ ]:
fact_sales[[
    "order_id",
    "customer_id",
    "order_status",
    "order_purchase_timestamp"
]].head()

,order_id,customer_id,order_status,order_purchase_timestamp
0,00010242fe8c5a6d1ba2dd792cb16214,3ce436f183e68e07877b285a838db11a,delivered,2017-09-13 08:59:02
1,00018f77f2f0320c557190d7a144bdd3,f6dd3ec061db4e3987629fe6b26e5cce,delivered,2017-04-26 10:53:06
2,000229ec398224ef6ca0657da4fc703e,6489ae5e4333f3693df5ad4372dab6d3,delivered,2018-01-14 14:33:31
3,00024acbcdf0a6daa1e931b038114c75,d4eb9395c8c0431ee92fce09860c5a06,delivered,2018-08-08 10:00:35
4,00042b26cf59d7ce69dfabb4e55b4fd9,58dbd0b2d70206bf40e62cd34e84d795,delivered,2017-02-04 13:57:51

In [ ]:
fact_sales["customer_id"].isnull().sum()

np.int64(0)

In [ ]:
customers = datasets["olist_customers_dataset"].copy()

customers.columns

Index(['customer_id', 'customer_unique_id', 'customer_zip_code_prefix',
       'customer_city', 'customer_state'],
      dtype='object')

In [ ]:
customers = datasets["olist_customers_dataset"].copy()

fact_sales = fact_sales.merge(
    customers,
    on="customer_id",
    how="left"
)

In [ ]:
print(fact_sales.shape)

(112650, 29)

In [ ]:
fact_sales["customer_state"].isnull().sum()

np.int64(0)

In [ ]:
fact_sales[[
    "customer_id",
    "customer_unique_id",
    "customer_city",
    "customer_state"
]].head()

,customer_id,customer_unique_id,customer_city,customer_state
0,3ce436f183e68e07877b285a838db11a,871766c5855e863f6eccc05f988b23cb,campos dos goytacazes,RJ
1,f6dd3ec061db4e3987629fe6b26e5cce,eb28e67c4c0b83846050ddfb8a35d051,santa fe do sul,SP
2,6489ae5e4333f3693df5ad4372dab6d3,3818d81c6709e39d06b2738a8d3a2474,para de minas,MG
3,d4eb9395c8c0431ee92fce09860c5a06,af861d436cfc08b2c2ddefd0ba074622,atibaia,SP
4,58dbd0b2d70206bf40e62cd34e84d795,64b576fb70d441e8f1b2d7d446e483c5,varzea paulista,SP

In [ ]:
products = datasets["olist_products_dataset"].copy()

products.columns

Index(['product_id', 'product_category_name', 'product_name_lenght',
       'product_description_lenght', 'product_photos_qty', 'product_weight_g',
       'product_length_cm', 'product_height_cm', 'product_width_cm'],
      dtype='object')

In [ ]:
products = datasets["olist_products_dataset"].copy()

fact_sales = fact_sales.merge(
    products,
    on="product_id",
    how="left"
)

In [ ]:
print(fact_sales.shape)

(112650, 37)

In [ ]:
fact_sales["product_category_name"].isnull().sum()

np.int64(1603)

In [ ]:
fact_sales[[
    "product_id",
    "product_category_name",
    "product_weight_g"
]].head()

                         product_id product_category_name  product_weight_g
0  4244733e06e7ecb4970a6e2683c13e61            cool_stuff             650.0
1  e5f2d52b802189ee658865ca93d83a8f              pet_shop           30000.0
2  c777355d18b72b67abbeef9df44fd0fd      moveis_decoracao            3050.0
3  7634da152a4610f1595efa32f14722fc            perfumaria             200.0
4  ac6c3623068f30de03045865e4e10089    ferramentas_jardim            3750.0

In [ ]:
fact_sales.shape

(112650, 37)

In [ ]:
sellers = datasets["olist_sellers_dataset"].copy()

fact_sales = fact_sales.merge(
    sellers,
    on="seller_id",
    how="left"
)

In [ ]:
print(fact_sales.shape)

fact_sales["seller_state"].isnull().sum()

(112650, 40)

np.int64(0)

In [ ]:
payments = datasets["olist_order_payments_dataset"].copy()

payments.head()

,order_id,payment_sequential,payment_type,payment_installments,payment_value
0,b81ef226f3fe1789b1e8b2acac839d17,1,credit_card,8,99.33
1,a9810da82917af2d9aefd1278f1dcfa0,1,credit_card,1,24.39
2,25e8ea4e93396b6fa0d3dd708e76c1bd,1,credit_card,1,65.71
3,ba78997921bbcdc1373bb41e913ab953,1,credit_card,8,107.78
4,42fdf880ba16b47b59251dd489d4441a,1,credit_card,2,128.45

In [ ]:
payments.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 103886 entries, 0 to 103885
Data columns (total 5 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   order_id              103886 non-null  object
 1   payment_sequential    103886 non-null  int64
 2   payment_type          103886 non-null  object
 3   payment_installments  103886 non-null  int64
 4   payment_value         103886 non-null  float64
dtypes: float64(1), int64(2), object(2)
memory usage: 4.0+ MB

In [ ]:
payments.groupby("order_id").size().value_counts().sort_index()

1     96479
2      2382
3       301
4       108
5        52
6        36
7        28
8        11
9         9
10        5
11        8
12        8
13        3
14        2
15        2
19        2
21        1
22        1
26        1
29        1
Name: count, dtype: int64

In [ ]:
payments.columns

Index(['order_id', 'payment_sequential', 'payment_type',
       'payment_installments', 'payment_value'],
      dtype='object')

In [ ]:
payments = datasets["olist_order_payments_dataset"].copy()

payment_summary = (
    payments
    .groupby("order_id", as_index=False)
    .agg(
        total_payment=("payment_value", "sum"),
        max_installments=("payment_installments", "max"),
        payment_count=("payment_sequential", "count")
    )
)

In [ ]:
payment_summary.shape

(99440, 4)

In [ ]:
payment_summary.head()

,order_id,total_payment,max_installments,payment_count
0,00010242fe8c5a6d1ba2dd792cb16214,72.19,2,1
1,00018f77f2f0320c557190d7a144bdd3,259.83,3,1
2,000229ec398224ef6ca0657da4fc703e,216.87,5,1
3,00024acbcdf0a6daa1e931b038114c75,25.78,2,1
4,00042b26cf59d7ce69dfabb4e55b4fd9,218.04,3,1

In [ ]:
fact_sales = fact_sales.merge(
    payment_summary,
    on="order_id",
    how="left"
)

In [ ]:
print(fact_sales.shape)

(112650, 43)

In [ ]:
fact_sales.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 112650 entries, 0 to 112649
Data columns (total 43 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   order_id                       112650 non-null  object
 1   order_item_id                  112650 non-null  int64
 2   product_id                     112650 non-null  object
 3   seller_id                      112650 non-null  object
 4   shipping_limit_date            112650 non-null  object
 5   price                          112650 non-null  float64
 6   freight_value                  112650 non-null  float64
 7   customer_id                    112650 non-null  object
 8   order_status                   112650 non-null  object
 9   order_purchase_timestamp       112650 non-null  datetime64[ns]
 10  order_approved_at              112635 non-null  datetime64[ns]
 11  order_delivered_carrier_date   111456 non-null  datetime64[ns]
 12  order_delivered_customer_date  110196 non-null  datetime64[ns]
 13  order_estimated_delivery_date  112650 non-null  datetime64[ns]
 14  order_year                     112650 non-null  int32
 15  order_quarter                  112650 non-null  int32
 16  order_month                    112650 non-null  int32
 17  order_month_name               112650 non-null  object
 18  order_day                      112650 non-null  int32
 19  order_day_name                 112650 non-null  object
 20  order_week                     112650 non-null  int64
 21  order_weekday                  112650 non-null  int32
 22  delivery_days                  110196 non-null  float64
 23  delay_days                     110196 non-null  float64
 24  delivery_status                112650 non-null  object
 25  customer_unique_id             112650 non-null  object
 26  customer_zip_code_prefix       112650 non-null  int64
 27  customer_city                  112650 non-null  object
 28  customer_state                 112650 non-null  object
 29  product_category_name          111047 non-null  object
 30  product_name_lenght            111047 non-null  float64
 31  product_description_lenght     111047 non-null  float64
 32  product_photos_qty             111047 non-null  float64
 33  product_weight_g               112632 non-null  float64
 34  product_length_cm              112632 non-null  float64
 35  product_height_cm              112632 non-null  float64
 36  product_width_cm               112632 non-null  float64
 37  seller_zip_code_prefix         112650 non-null  int64
 38  seller_city                    112650 non-null  object
 39  seller_state                   112650 non-null  object
 40  total_payment                  112647 non-null  float64
 41  max_installments               112647 non-null  float64
 42  payment_count                  112647 non-null  float64
dtypes: datetime64[ns](5), float64(14), int32(5), int64(4), object(15)
memory usage: 34.8+ MB

In [ ]:
fact_sales.columns.tolist()

['order_id',
 'order_item_id',
 'product_id',
 'seller_id',
 'shipping_limit_date',
 'price',
 'freight_value',
 'customer_id',
 'order_status',
 'order_purchase_timestamp',
 'order_approved_at',
 'order_delivered_carrier_date',
 'order_delivered_customer_date',
 'order_estimated_delivery_date',
 'order_year',
 'order_quarter',
 'order_month',
 'order_month_name',
 'order_day',
 'order_day_name',
 'order_week',
 'order_weekday',
 'delivery_days',
 'delay_days',
 'delivery_status',
 'customer_unique_id',
 'customer_zip_code_prefix',
 'customer_city',
 'customer_state',
 'product_category_name',
 'product_name_lenght',
 'product_description_lenght',
 'product_photos_qty',
 'product_weight_g',
 'product_length_cm',
 'product_height_cm',
 'product_width_cm',
 'seller_zip_code_prefix',
 'seller_city',
 'seller_state',
 'total_payment',
 'max_installments',
 'payment_count']

In [ ]:
dim_customers = fact_sales[
    [
        "customer_id",
        "customer_unique_id",
        "customer_zip_code_prefix",
        "customer_city",
        "customer_state"
    ]
].drop_duplicates()

print(dim_customers.shape)
dim_customers.head()

(98666, 5)

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
0,3ce436f183e68e07877b285a838db11a,871766c5855e863f6eccc05f988b23cb,28013,campos dos goytacazes,RJ
1,f6dd3ec061db4e3987629fe6b26e5cce,eb28e67c4c0b83846050ddfb8a35d051,15775,santa fe do sul,SP
2,6489ae5e4333f3693df5ad4372dab6d3,3818d81c6709e39d06b2738a8d3a2474,35661,para de minas,MG
3,d4eb9395c8c0431ee92fce09860c5a06,af861d436cfc08b2c2ddefd0ba074622,12952,atibaia,SP
4,58dbd0b2d70206bf40e62cd34e84d795,64b576fb70d441e8f1b2d7d446e483c5,13226,varzea paulista,SP

In [ ]:
dim_products = fact_sales[
    [
        "product_id",
        "product_category_name",
        "product_name_lenght",
        "product_description_lenght",
        "product_photos_qty",
        "product_weight_g",
        "product_length_cm",
        "product_height_cm",
        "product_width_cm"
    ]
].drop_duplicates()

print(dim_products.shape)

(32951, 9)

In [ ]:
dim_sellers = fact_sales[
    [
        "seller_id",
        "seller_zip_code_prefix",
        "seller_city",
        "seller_state"
    ]
].drop_duplicates()

print(dim_sellers.shape)

(3095, 4)

In [ ]:
start_date = fact_sales["order_purchase_timestamp"].min().normalize()
end_date = fact_sales["order_purchase_timestamp"].max().normalize()

dim_date = pd.DataFrame({
    "Date": pd.date_range(start=start_date, end=end_date, freq="D")
})

In [ ]:
dim_date["Year"] = dim_date["Date"].dt.year
dim_date["Quarter"] = dim_date["Date"].dt.quarter
dim_date["Quarter_Name"] = "Q" + dim_date["Quarter"].astype(str)

dim_date["Month"] = dim_date["Date"].dt.month
dim_date["Month_Name"] = dim_date["Date"].dt.month_name()

dim_date["Day"] = dim_date["Date"].dt.day
dim_date["Day_Name"] = dim_date["Date"].dt.day_name()

dim_date["Week"] = dim_date["Date"].dt.isocalendar().week.astype(int)

dim_date["Weekday"] = dim_date["Date"].dt.weekday + 1

dim_date["Is_Weekend"] = dim_date["Weekday"].isin([6, 7])

dim_date["Year_Month"] = dim_date["Date"].dt.strftime("%Y-%m")

In [ ]:
print(dim_date.shape)

dim_date.head()

(730, 12)

,Date,Year,Quarter,Quarter_Name,Month,Month_Name,Day,Day_Name,Week,Weekday,Is_Weekend,Year_Month
0,2016-09-04,2016,3,Q3,9,September,4,Sunday,35,7,True,2016-09
1,2016-09-05,2016,3,Q3,9,September,5,Monday,36,1,False,2016-09
2,2016-09-06,2016,3,Q3,9,September,6,Tuesday,36,2,False,2016-09
3,2016-09-07,2016,3,Q3,9,September,7,Wednesday,36,3,False,2016-09
4,2016-09-08,2016,3,Q3,9,September,8,Thursday,36,4,False,2016-09

In [ ]:
fact_sales_final = fact_sales[
    [
        "order_id",
        "order_item_id",
        "product_id",
        "seller_id",
        "customer_id",

        "order_status",

        "order_purchase_timestamp",
        "order_approved_at",
        "order_delivered_carrier_date",
        "order_delivered_customer_date",
        "order_estimated_delivery_date",

        "price",
        "freight_value",

        "delivery_days",
        "delay_days",
        "delivery_status",

        "total_payment",
        "max_installments",
        "payment_count"
    ]
].copy()

In [ ]:
fact_sales_final.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 112650 entries, 0 to 112649
Data columns (total 19 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   order_id                       112650 non-null  object
 1   order_item_id                  112650 non-null  int64
 2   product_id                     112650 non-null  object
 3   seller_id                      112650 non-null  object
 4   customer_id                    112650 non-null  object
 5   order_status                   112650 non-null  object
 6   order_purchase_timestamp       112650 non-null  datetime64[ns]
 7   order_approved_at              112635 non-null  datetime64[ns]
 8   order_delivered_carrier_date   111456 non-null  datetime64[ns]
 9   order_delivered_customer_date  110196 non-null  datetime64[ns]
 10  order_estimated_delivery_date  112650 non-null  datetime64[ns]
 11  price                          112650 non-null  float64
 12  freight_value                  112650 non-null  float64
 13  delivery_days                  110196 non-null  float64
 14  delay_days                     110196 non-null  float64
 15  delivery_status                112650 non-null  object
 16  total_payment                  112647 non-null  float64
 17  max_installments               112647 non-null  float64
 18  payment_count                  112647 non-null  float64
dtypes: datetime64[ns](5), float64(7), int64(1), object(6)
memory usage: 16.3+ MB

In [ ]:
fact_sales_final["Date"] = fact_sales_final[
    "order_purchase_timestamp"
].dt.normalize()

In [ ]:
fact_sales_final[["order_purchase_timestamp", "Date"]].head()

  order_purchase_timestamp       Date
0      2017-09-13 08:59:02 2017-09-13
1      2017-04-26 10:53:06 2017-04-26
2      2018-01-14 14:33:31 2018-01-14
3      2018-08-08 10:00:35 2018-08-08
4      2017-02-04 13:57:51 2017-02-04

In [ ]:
print("Fact :", fact_sales_final.shape)
print("Customers :", dim_customers.shape)
print("Products :", dim_products.shape)
print("Sellers :", dim_sellers.shape)
print("Date :", dim_date.shape)

Fact : (112650, 20)
Customers : (98666, 5)
Products : (32951, 9)
Sellers : (3095, 4)
Date : (730, 12)

In [ ]:
category_columns = [
    "order_id",
    "customer_id",
    "product_id",
    "seller_id",
    "order_status",
    "delivery_status"
]

for col in category_columns:
    fact_sales_final[col] = fact_sales_final[col].astype("category")

In [ ]:
import os

os.makedirs("clean_data", exist_ok=True)

In [ ]:
fact_sales_final.to_csv("clean_data/Fact_Sales.csv", index=False)

dim_customers.to_csv("clean_data/Dim_Customers.csv", index=False)

dim_products.to_csv("clean_data/Dim_Products.csv", index=False)

dim_sellers.to_csv("clean_data/Dim_Sellers.csv", index=False)

dim_date.to_csv("clean_data/Dim_Date.csv", index=False)

In [ ]:
import zipfile

with zipfile.ZipFile("Clean_Data.zip", "w") as zipf:
    for file in os.listdir("clean_data"):
        zipf.write(
            os.path.join("clean_data", file),
            arcname=file
        )

print("Done")

Done

In [ ]:
from google.colab import files

files.download("Clean_Data.zip")

**Finally 😤**